Bump minimum supported version and tested upto for WC and WP
woocommerce/woocommerce-gateway-payfast pull request #131
Opened 2023-04-27 11:30 UTC by kirtangajjar

**Issue**: #208

---

### Description

 * Bump WooCommerce "tested up to" version 7.6
 * Bump WordPress minimum supported version from 5.6 to 5.8
 * Bump WordPress "tested up to" version 6.2.

### Steps to Test

- [ ] Set up Payment Gateway with sandbox credentials
- [ ] Place an order with the PayFast payment gateway.
- [ ] Place an order for a subscription product with the PayFast payment gateway and renew the subscription.

### Documentation

- [ ] This PR needs documentation (has the "Documentation" label).

### Changelog Entry

> Dev - Bump WooCommerce "tested up to" version 7.6.
> Dev - Bump WordPress minimum supported version from 5.6 to 5.8.
> Dev - Bump WordPress "tested up to" version 6.2.

Closes #208.

2023-04-27 15:07 UTC, iamdharmesh requested changes
@kirtangajjar Thanks for the PR. The changes look good to me. Could you please help with bump versions in readme.txt as well?


https://github.com/woocommerce/woocommerce-gateway-payfast/blob/75da864d7b72d98207eacdefbd3ff15fa9f53120/readme.txt#L4-L5

Thanks

2023-04-27 20:34 UTC, kirtangajjar commented
@iamdharmesh Thanks for catching that! Done!

2023-04-28 04:55 UTC, iamdharmesh approved these changes

2023-05-10 13:15 UTC, ankitguptaindia commented
**Regression+Smoke Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.2
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.7.0
* PHP: 8.0.22 
* Web Server: Nginx
* Browser: Chrome - Version 112 


</Details>


Tested with Archive File created via 

```php woorelease.phar build https://github.com/woocommerce/woocommerce-gateway-payfast/tree/smoke-testing```

- Composer version - 2.3.5
- npm version - 6.14.15
- node version - v14.18.0

#### Please note that this plugin is tested with the build created by specified versions of Composer, Node, and NPM. 



**Status-** Tested plugin thoroughly and checked all main functional cases of the plugin. Found all cases working as expected. 
Ready to Merge 🚀

2023-05-10 13:16 UTC, ankitguptaindia approved these changes

2023-05-12 13:37 UTC, merged