Update WC tested upto 7.8
woocommerce/woocommerce-gateway-payfast pull request #138
Opened 2023-06-20 21:00 UTC by kirtangajjar

**Issue**: #133 

---

### Description

 - Bump WooCommerce "tested up to" version 7.8.
 - Bump WooCommerce minimum supported version from X.X to 7.2.
 - Bump WordPress minimum supported version from X.X to 6.1.

### Steps to Test

Smoke test with WC 7.8:
- [ ] Set up Payment Gateway with sandbox credentials
- [ ] Place an order with the PayFast payment gateway.
- [ ] Place an order for a subscription product with the PayFast payment gateway and renew the subscription.

### Documentation

- [ ] This PR needs documentation (has the "Documentation" label).

### Changelog Entry

> Dev - Bump WooCommerce "tested up to" version 7.8.
> Dev - Bump WooCommerce minimum supported version from X.X to 7.2.
> Dev - Bump WordPress minimum supported version from X.X to 6.1.

Closes #133

2023-06-21 13:09 UTC, iamdharmesh requested changes
Thanks for the PR @kirtangajjar, left one minor note and we may also want to update requires at least in readme.md [here](https://github.com/woocommerce/woocommerce-gateway-payfast/blob/trunk/README.md?plain=1#L9)?

Apart from that, All looks good.
Thanks

2023-06-21 13:09 UTC, iamdharmesh commented on readme.txt
> +Requires at least: 6.2
```suggestion
Requires at least: 6.1
```

2023-06-21 13:29 UTC, kirtangajjar commented
@iamdharmesh Changes accepted :)

2023-06-22 12:37 UTC, iamdharmesh commented
Thanks @kirtangajjar, we may want to update requires at least in readme.md [here](https://github.com/woocommerce/woocommerce-gateway-payfast/blob/trunk/README.md?plain=1&rgh-link-date=2023-06-21T13%3A09%3A03Z#L9).

2023-06-22 13:57 UTC, kirtangajjar commented
@iamdharmesh Apologies, I already made the change , but I forgot to push. Please check now :sweat_smile:

2023-06-26 14:13 UTC, iamdharmesh approved these changes
Thanks @kirtangajjar

2023-06-30 15:29 UTC, merged